version: '3.8'

services:
  web:
    build: .
    # platform: linux/amd64
    container_name: cakephp2_web
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:5.6
    # platform: linux/amd64
    container_name: cakephp2_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: cakephp_db
      MYSQL_USER: cakeuser
      MYSQL_PASSWORD: cakepass
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
